/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ListYourCdcRouteImport } from './routes/list-your-cdc'
import { Route as ForCdcsRouteImport } from './routes/for-cdcs'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ListYourCdcRoute = ListYourCdcRouteImport.update({
  id: '/list-your-cdc',
  path: '/list-your-cdc',
  getParentRoute: () => rootRouteImport,
} as any)
const ForCdcsRoute = ForCdcsRouteImport.update({
  id: '/for-cdcs',
  path: '/for-cdcs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/for-cdcs': typeof ForCdcsRoute
  '/list-your-cdc': typeof ListYourCdcRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/for-cdcs': typeof ForCdcsRoute
  '/list-your-cdc': typeof ListYourCdcRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/for-cdcs': typeof ForCdcsRoute
  '/list-your-cdc': typeof ListYourCdcRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/for-cdcs' | '/list-your-cdc' | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/for-cdcs' | '/list-your-cdc' | '/sitemap.xml'
  id: '__root__' | '/' | '/for-cdcs' | '/list-your-cdc' | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForCdcsRoute: typeof ForCdcsRoute
  ListYourCdcRoute: typeof ListYourCdcRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-your-cdc': {
      id: '/list-your-cdc'
      path: '/list-your-cdc'
      fullPath: '/list-your-cdc'
      preLoaderRoute: typeof ListYourCdcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-cdcs': {
      id: '/for-cdcs'
      path: '/for-cdcs'
      fullPath: '/for-cdcs'
      preLoaderRoute: typeof ForCdcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForCdcsRoute: ForCdcsRoute,
  ListYourCdcRoute: ListYourCdcRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
